### ISSUE TITLE
Please properly cite published paper

### ISSUE THREAD

**Issue by yechengxi** [YooshinCho/pytorch_ConvUnitOptimization#1]
Hello, it appears the design of putting the whitening before the linear transform was proposed in earlier work. It will be nice if you could properly cite the previous work.

See. eq4 or Sec 4.5.1. Code is also avaiable.
https://openreview.net/pdf?id=rkeu30EtvS

**Comment by YooshinCho** [comment]
Hello, I will properly cite the paper and re-upload as soon as possible.
Thank you for letting me know.
